### ISSUE TITLE
zcml condition does not work

### ISSUE THREAD

**Issue by mbaechtold** [plone/plone.app.collection#33]
According to https://dev.plone.org/ticket/13723 the following zcml condition does not work:

```
 <browser:page zcml:condition="not-have Plone-43"
      name="RSS"
      permission="zope2.View"
      for="plone.app.collection.interfaces.ICollection"
      template="templates/rss.pt"
      />
```

This overrides the view `RSS` from `Products.CMFPlone/browser/syndication` even if Plone 4.3 is installed.

I'll try to provide a pull request.

**Comment by gforcada** [comment]
Hi @mbaechtold, it seems that you may have not signed a [Contributors Agreement with the Plone Foundation](https://plone.org/foundation/contributors-agreement)? At least you are not part of the plone organization, so before sending that pull request it would be better (to speed up the pull request) that you signed it.

If you already have signed it, please let us know so we can add you to the plone organization :-)

**Comment by mbaechtold** [comment]
Hi @gforcada, I just have sent the Contributors Agreement to agreements@plone.org.

**Comment by gforcada** [comment]
Hi @mbaechtold @ableeb is (I think) the one processing CLA agreements, as soon as he replies to this thread we can review and merge your changes.

Thanks for signing it and welcome to Plone!

**Comment by ableeb** [comment]
@mbaechtold Welcome! @gforcada Martin's Contributors Agreement has been processed.

**Comment by gforcada** [comment]
@mbaechtold welcome! Now for the pull request :-)

**Comment by mbaechtold** [comment]
Closing this issue due to its age.
