### ISSUE TITLE
Table headings in tabular view use field id's not titles

### ISSUE THREAD

**Issue by instification** [plone/plone.app.collection#52]
When you use the tabular view, your table headings are the id of the fields you have selected.

It would be better if the content schema is introspected and titles are used instead. 

A better enhancement might be to allow the user to choose what to display (id or title) when creating/editing the collection.

**Comment by vincentfretin** [comment]
This is fixed from the dexterity collection (plone.app.contenttypes) in Plone 5.2.2.
